In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv('heart_cleveland_upload.csv')

In [3]:
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,40,1,3,152,223,0,0,181,0,0.0,0,0,2,1
293,39,1,3,118,219,0,0,140,0,1.2,1,0,2,1
294,35,1,3,120,198,0,0,130,1,1.6,1,0,2,1
295,35,0,3,138,183,0,0,182,0,1.4,0,0,0,0
296,35,1,3,126,282,0,2,156,1,0.0,0,0,2,1

In [8]:
data = pd.get_dummies(data, columns=['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal'])

# Normalize the continuous variables
continuous_vars = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
data[continuous_vars] = (data[continuous_vars] - data[continuous_vars].mean()) / data[continuous_vars].std()

# Split the data into training and testing sets

In [12]:
data# normalized data

,age,trestbps,chol,thalach,oldpeak,condition,sex_0,sex_1,cp_0,cp_1,...,slope_0,slope_1,slope_2,ca_0,ca_1,ca_2,ca_3,thal_0,thal_1,thal_2
0,1.597606,1.593577,-0.256746,-0.810726,-0.819430,0,0,1,1,0,...,0,1,0,0,1,0,0,1,0,0
1,1.597606,0.467629,-0.160588,0.061054,0.638393,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
2,1.266105,1.030603,-0.410599,-1.551739,1.324427,0,1,0,1,0,...,0,0,1,1,0,0,0,1,0,0
3,1.155604,0.355034,0.666374,1.063601,0.295376,1,0,1,1,0,...,0,1,0,0,1,0,0,1,0,0
4,1.045104,-1.221294,-0.699074,-0.244069,0.638393,0,0,1,1,0,...,0,1,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,-1.606907,1.143198,-0.468294,1.368724,-0.905184,1,0,1,0,0,...,1,0,0,1,0,0,0,0,0,1
293,-1.717408,-0.770914,-0.545221,-0.418425,0.123867,1,0,1,0,0,...,0,1,0,1,0,0,0,0,0,1
294,-2.159410,-0.658320,-0.949086,-0.854315,0.466884,1,0,1,0,0,...,0,1,0,1,0,0,0,0,0,1
295,-2.159410,0.355034,-1.237561,1.412313,0.295376,0,1,0,0,0,...,1,0,0,1,0,0,0,1,0,0
296,-2.159410,-0.320535,0.666374,0.278999,-0.905184,1,0,1,0,0,...,1,0,0,1,0,0,0,0,0,1

In [18]:
import numpy as np

data = pd.read_csv('heart.csv')

X = data[:, :-1]
y = data[:, -1]

def svm(X, y, C, epochs, learning_rate):
    # Initialize the weights and bias
    w = np.zeros(X.shape[1])
    b = 0

    for epoch in range(epochs):
        for i in range(X.shape[0]):
            margin = y[i] * (np.dot(w, X[i]) + b)

            if margin < 1:
                w = w - learning_rate * (2 * C * np.dot(w, X[i]) - y[i] * X[i])
                b = b - learning_rate * (-2 * C * y[i])
            else:
                w = w - learning_rate * 2 * C * np.dot(w, X[i])

    return w, b

C = 1
epochs = 1000
learning_rate = 0.01

# Train the SVM
w, b = svm(X, y, C, epochs, learning_rate)

# Print the weights and bias
print('Weights:', w) 
print('Bias:', b)

TypeError: '(slice(None, None, None), slice(None, -1, None))' is an invalid key

In [11]:
from sklearn.svm import SVC

In [14]:
model=SVC()

In [ ]:
model.fit()